<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_basics"
 *
 * Auto generated by Extension Builder 2014-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Basics',
	'description' => 'Extension with some basic extensions for BE and FE',
	'category' => 'be',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel.de',
	'author_company' => 'RKW Kompetenzzentrum',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '8.7.9',
    'constraints' => [
		'depends' => [
			'typo3' => '8.7.0-8.7.99',
            'filemetadata' => '8.7.0-8.7.99',
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
